In [3]:
import numpy as np

print(f'Version de NumPy: {np.__version__}')

Version de NumPy: 2.3.0


In [5]:
#Crear un arreglo en 1D desde lista
lista = [1, 2, 3, 4, 5]
array_1d = np.array(lista)
print(f'Arreglo 1D: {array_1d}')

#Crear un arreglo en 2D desde lista de listas
lista_2d = [[1, 2, 3], [4, 5, 6]]
array_2d = np.array(lista_2d)
print(f'Arreglo 2D: {array_2d}')

Arreglo 1D: [1 2 3 4 5]
Arreglo 2D: [[1 2 3]
 [4 5 6]]


In [ ]:
#array de ceros
zero = np.zeros((3, 4)) #[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
print(zero)

#array de unos
ones = np.ones((2, 3)) #[[1, 1, 1], [1, 1, 1]]
print(ones)

#array con valor constante
full = np.full((2,2), 7) #[[7, 7], [7, 7]]
print(full)

#matriz identidad
identity = np.eye(3) # [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
print(identity)

#secuencia con paso especifico
arange = np.arange(0, 10, 2) # [0, 2, 4, 6, 8]
print(arange)

#secuencia con números específico de elementos
linspace = np.linspace(0, 1, 5) # [0. , 0.25, 0.5 , 0.75, 1. ]
print(linspace)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [8]:
#Matriz aleatoria
random = np.random.random((2, 3))
print(random)

#Matriz aleatoria con números enteros
random_int = np.random.randint(0, 10, (2, 3))
print(random_int)

#Matriz distribución normal
normal_dist = np.random.normal(0, 1, (2, 3))
print(normal_dist)

[[0.85424108 0.76627404 0.3390346 ]
 [0.80619609 0.16536765 0.285852  ]]
[[0 6 7]
 [4 3 6]]
[[ 0.61030838 -1.52484744  0.46039654]
 [-0.97131085 -1.29847958  0.98663283]]


In [9]:
#Arreglo aleatorio
array = np.random.randint(0, 10, (3, 3))
print(f"Arreglo aleatorio:\n{array}")

#Propiedades del arreglo
print(f"Dimensión: {array.ndim}")
print(f"Forma: {array.shape}")
print(f"Tamaño: {array.size}")
print(f"Tipo de dato: {array.dtype}")

#Arreglo por capas
print(f"capa 0: {array[0]}")
print(f"capa 1: {array[1]}")
print(f"capa 2: {array[2]}")

Arreglo aleatorio:
[[5 7 2]
 [6 4 5]
 [6 5 5]]
Dimensión: 2
Forma: (3, 3)
Tamaño: 9
Tipo de dato: int32
capa 0: [5 7 2]
capa 1: [6 4 5]
capa 2: [6 5 5]


In [10]:
#Arreglo en 1D
array1 =  np.arange(12)
print(f"Arreglo 1D:\n{array1}")

#Reshape a 2d
array_2d_reshape = array1.reshape((3, 4))
print(f"Arreglo 2D reshape:\n{array_2d_reshape}")

#Transponer el arreglo
transposed = array_2d_reshape.T
print(f"Arreglo transpuesto:\n{transposed}")

Arreglo 1D:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Arreglo 2D reshape:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Arreglo transpuesto:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
